baseURL = 'https://192.168.1.4/'
languageCode = 'en-us'
title = 'Auroras Book Blog'
theme = 'hugo-papermod'

[params.profileMode]
enabled = true
title = "Aurora Emini"
subtitle = "Hello, I am currently a medical student and have a book blog on the side"
imageUrl = "https://i.postimg.cc/HnqyLJkz/IMG-1937.jpg"
imageTitle = "<title of image as alt>"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Book Review"
  url = "/posts"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"

[[params.socialIcons]]
name = "Instagram"
url = "<link>"

[[params.socialIcons]]
name = "Youtube"
url = "<link2>"

[[params.socialIcons]]
name = "LinkedIn"
url = "<link>"

[params]
ShowShareButtons = true
ShowBreadCrumbs = true
ShowReadingTime = true


